### ISSUE TITLE
Parse capitals in gear class names as separate words

### ISSUE THREAD

**Issue by thebrightspark** [bvanseg/KotlinCommons#7]
**Is your feature request related to a problem? Please describe.**
When a gear class name contains multiple words starting with capital letters, they are not parsed as separate words for the gear name,

**Describe the solution you'd like**
Gear names use capitals to separate words.

**Describe alternatives you've considered**
Explicitly defining gear names, but is rather tedius and the suggested feature is intuitive and convenient.

**Additional context**
N/A

**Comment by bvanseg** [comment]
Resolved with 0d2377c8672a5614ddc33a9a003b56dbff3530f1. Name the gears manually via the `Gear` class' constructor from now on to get your desired name.
